AllCops:
  NewCops: enable

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/TrailingWhitespace:
  Enabled: false

Layout/EndOfLine:
  Enabled: False

Layout/LineLength:
  Max: 160

Metrics/MethodLength:
  Max: 25

Metrics/BlockLength:
  Max: 120

Metrics/AbcSize:
  Enabled: False